version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
    overwrite: true
hooks:
  BeforeInstall:
    - location: dependencies/before.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: dependencies/after.sh
      timeout: 300
      runas: root